name: AutPGrp
version: 1.10.2
date: 2020-01-28
description: |
    Computing the Automorphism Group of a p-Group

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Eamonn O'Brien
      url: http://www.math.auckland.ac.nz/~obrien

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/autpgrp/
readme: README
packageinfo: https://gap-packages.github.io/autpgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/autpgrp/releases/download/v1.10.2/autpgrp-1.10.2.tar.gz

abstract: |
    The <span class="pkgname">AutPGrp</span> package introduces a new function to compute the automorphism group of a finite $p$-group. The underlying algorithm is a refinement of the methods described in O'Brien (1995). In particular, this implementation is more efficient in both time and space requirements and hence has a wider range of applications than the ANUPQ method. Our package is written in GAP code and it makes use of a number of methods from the GAP library such as the MeatAxe for matrix groups and permutation group functions. We have compared our method to the others available in GAP. Our package usually out-performs all but the method designed for finite abelian groups. We note that our method uses the small groups library in certain cases and hence our algorithm is more effective if the small groups library is installed.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
